[environments.default]
store = "nutricost-shop.myshopify.com"

[environments.dev]
store = "nutricost.myshopify.com"
theme = "156821815526"

[environments.production]
store = "nutricost-shop.myshopify.com"
theme = "LIVE_THEME_ID"
